[package]
name = "ui_utils"
version = "0.1.0"
authors = ["theaaaaaaa <theah0032@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.21.0"
unicode-segmentation = "1.8.0"